/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsToolNameRouteImport } from './routes/tools/$toolName'
import { ServerRoute as ApiToolsToolNameServerRouteImport } from './routes/api/tools.$toolName'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolNameRoute = ToolsToolNameRouteImport.update({
  id: '/tools/$toolName',
  path: '/tools/$toolName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsToolNameServerRoute = ApiToolsToolNameServerRouteImport.update({
  id: '/api/tools/$toolName',
  path: '/api/tools/$toolName',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/$toolName': typeof ToolsToolNameRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/$toolName': typeof ToolsToolNameRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/$toolName': typeof ToolsToolNameRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/$toolName' | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/$toolName' | '/tools'
  id: '__root__' | '/' | '/tools/$toolName' | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsToolNameRoute: typeof ToolsToolNameRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/tools/$toolName': typeof ApiToolsToolNameServerRoute
}
export interface FileServerRoutesByTo {
  '/api/tools/$toolName': typeof ApiToolsToolNameServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/tools/$toolName': typeof ApiToolsToolNameServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/tools/$toolName'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/tools/$toolName'
  id: '__root__' | '/api/tools/$toolName'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiToolsToolNameServerRoute: typeof ApiToolsToolNameServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolName': {
      id: '/tools/$toolName'
      path: '/tools/$toolName'
      fullPath: '/tools/$toolName'
      preLoaderRoute: typeof ToolsToolNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/tools/$toolName': {
      id: '/api/tools/$toolName'
      path: '/api/tools/$toolName'
      fullPath: '/api/tools/$toolName'
      preLoaderRoute: typeof ApiToolsToolNameServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsToolNameRoute: ToolsToolNameRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiToolsToolNameServerRoute: ApiToolsToolNameServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
