/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsComponentNameRouteImport } from './routes/docs/$componentName'
import { Route as ToolsToolNameIndexRouteImport } from './routes/tools/$toolName/index'
import { Route as ToolsToolNameEditRouteImport } from './routes/tools/$toolName/edit'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentNameRoute = DocsComponentNameRouteImport.update({
  id: '/$componentName',
  path: '/$componentName',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ToolsToolNameIndexRoute = ToolsToolNameIndexRouteImport.update({
  id: '/tools/$toolName/',
  path: '/tools/$toolName/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolNameEditRoute = ToolsToolNameEditRouteImport.update({
  id: '/tools/$toolName/edit',
  path: '/tools/$toolName/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/$componentName': typeof DocsComponentNameRoute
  '/docs/': typeof DocsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$toolName/edit': typeof ToolsToolNameEditRoute
  '/tools/$toolName/': typeof ToolsToolNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$componentName': typeof DocsComponentNameRoute
  '/docs': typeof DocsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/$toolName/edit': typeof ToolsToolNameEditRoute
  '/tools/$toolName': typeof ToolsToolNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/$componentName': typeof DocsComponentNameRoute
  '/docs/': typeof DocsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$toolName/edit': typeof ToolsToolNameEditRoute
  '/tools/$toolName/': typeof ToolsToolNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/$componentName'
    | '/docs/'
    | '/tools/'
    | '/tools/$toolName/edit'
    | '/tools/$toolName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$componentName'
    | '/docs'
    | '/tools'
    | '/tools/$toolName/edit'
    | '/tools/$toolName'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/$componentName'
    | '/docs/'
    | '/tools/'
    | '/tools/$toolName/edit'
    | '/tools/$toolName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  ToolsIndexRoute: typeof ToolsIndexRoute
  ToolsToolNameEditRoute: typeof ToolsToolNameEditRoute
  ToolsToolNameIndexRoute: typeof ToolsToolNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$componentName': {
      id: '/docs/$componentName'
      path: '/$componentName'
      fullPath: '/docs/$componentName'
      preLoaderRoute: typeof DocsComponentNameRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/tools/$toolName/': {
      id: '/tools/$toolName/'
      path: '/tools/$toolName'
      fullPath: '/tools/$toolName/'
      preLoaderRoute: typeof ToolsToolNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolName/edit': {
      id: '/tools/$toolName/edit'
      path: '/tools/$toolName/edit'
      fullPath: '/tools/$toolName/edit'
      preLoaderRoute: typeof ToolsToolNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteRouteChildren {
  DocsComponentNameRoute: typeof DocsComponentNameRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsComponentNameRoute: DocsComponentNameRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  ToolsIndexRoute: ToolsIndexRoute,
  ToolsToolNameEditRoute: ToolsToolNameEditRoute,
  ToolsToolNameIndexRoute: ToolsToolNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
