name: PR Checks

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    name: bun lint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - run: bun run lint
      - run: bun run format:check

  build-test:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - run: bun run build
      - run: bun run test
