name: PR Checks

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    name: Lint and Format Code
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - run: bun run lint
      - name: Format code
        env:
          NODE_OPTIONS: --experimental-strip-types
        run: bunx prettier . --write

  build-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - run: bun run build
      - run: bun run test
